[package]
name = "datafusion-over-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "39.0.0"
actix-web = "4"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }